<a href="https://colab.research.google.com/github/Hussy24/AI-Labs/blob/main/Hasnain_SmS_spam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df1 = pd.read_csv("/content/drive/MyDrive/spam.csv", encoding='latin-1') 

In [ ]:
df1

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [ ]:
df1['v1'] = df1.v1.map({'ham':0, 'spam':1})
df1

v1                                                 v2 Unnamed: 2  \
0      0  Go until jurong point, crazy.. Available only ...        NaN   
1      0                      Ok lar... Joking wif u oni...        NaN   
2      1  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      0  U dun say so early hor... U c already then say...        NaN   
4      0  Nah I don't think he goes to usf, he lives aro...        NaN   
...   ..                                                ...        ...   
5567   1  This is the 2nd time we have tried 2 contact u...        NaN   
5568   0              Will Ì_ b going to esplanade fr home?        NaN   
5569   0  Pity, * was in mood for that. So...any other s...        NaN   
5570   0  The guy did some bitching but I acted like i'd...        NaN   
5571   0                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [91]:
X= df1['v2'].to_numpy()
Y = df1['v1'].to_numpy()
y = Y.astype('int')

In [92]:
print("X")
print(X)
print("y")
print(y)

X
['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
 'Ok lar... Joking wif u oni...'
 "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"
 ... 'Pity, * was in mood for that. So...any other suggestions?'
 "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"
 'Rofl. Its true to its name']
y
[0 0 1 ... 0 0 0]


In [93]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
vec = CountVectorizer()

In [94]:
vec.fit(X)
vec.vocabulary_

{'go': 3550,
 'until': 8030,
 'jurong': 4350,
 'point': 5920,
 'crazy': 2327,
 'available': 1303,
 'only': 5537,
 'in': 4087,
 'bugis': 1751,
 'great': 3634,
 'world': 8489,
 'la': 4476,
 'buffet': 1749,
 'cine': 2048,
 'there': 7645,
 'got': 3594,
 'amore': 1069,
 'wat': 8267,
 'ok': 5504,
 'lar': 4512,
 'joking': 4318,
 'wif': 8392,
 'oni': 5533,
 'free': 3358,
 'entry': 2949,
 'wkly': 8447,
 'comp': 2165,
 'to': 7756,
 'win': 8405,
 'fa': 3087,
 'cup': 2386,
 'final': 3207,
 'tkts': 7743,
 '21st': 411,
 'may': 4930,
 '2005': 402,
 'text': 7595,
 '87121': 784,
 'receive': 6297,
 'question': 6190,
 'std': 7230,
 'txt': 7933,
 'rate': 6242,
 'apply': 1156,
 '08452810075over18': 77,
 'dun': 2802,
 'say': 6633,
 'so': 7024,
 'early': 2823,
 'hor': 3927,
 'already': 1042,
 'then': 7640,
 'nah': 5238,
 'don': 2712,
 'think': 7660,
 'he': 3781,
 'goes': 3558,
 'usf': 8075,
 'lives': 4665,
 'around': 1207,
 'here': 3831,
 'though': 7680,
 'freemsg': 3365,
 'hey': 3841,
 'darling': 2443,
 'it

In [95]:
import nltk
from nltk.tokenize import TweetTokenizer
from sklearn.feature_extraction.text import TfidfVectorizer
def tokenizer(text):
    tok = TweetTokenizer()
    return tok.tokenize(text)

vec = TfidfVectorizer(ngram_range=(1,1), stop_words='english', tokenizer=tokenizer)
vec.fit(X)
vec.vocabulary_

{'jurong': 4523,
 'point': 6078,
 ',': 13,
 'crazy': 2480,
 '..': 21,
 'available': 1486,
 'bugis': 1908,
 'n': 5413,
 'great': 3771,
 'world': 8655,
 'la': 4656,
 'e': 2976,
 'buffet': 1906,
 '...': 25,
 'cine': 2209,
 'got': 3732,
 'amore': 1265,
 'wat': 8437,
 'ok': 5676,
 'lar': 4693,
 'joking': 4490,
 'wif': 8558,
 'u': 8109,
 'oni': 5705,
 'free': 3494,
 'entry': 3105,
 '2': 471,
 'wkly': 8611,
 'comp': 2317,
 'win': 8572,
 'fa': 3231,
 'cup': 2537,
 'final': 3348,
 'tkts': 7905,
 '21st': 496,
 '2005': 486,
 '.': 15,
 'text': 7763,
 '87121': 937,
 'receive': 6462,
 'question': 6351,
 '(': 9,
 'std': 7399,
 'txt': 8093,
 'rate': 6405,
 ')': 10,
 't': 7634,
 '&': 7,
 "c's": 1954,
 'apply': 1342,
 '08452810075': 115,
 '18': 438,
 "'": 8,
 's': 6733,
 'dun': 2962,
 'say': 6804,
 'early': 2988,
 'hor': 4069,
 'c': 1953,
 'nah': 5425,
 "don't": 2873,
 'think': 7825,
 'goes': 3696,
 'usf': 8243,
 'lives': 4844,
 'freemsg': 3503,
 'hey': 3981,
 'darling': 2595,
 "it's": 4382,
 '3': 584,


In [96]:
print(vec.get_feature_names_out())
print(len(vec.get_feature_names_out()))

['!' '"' '#' ... 'ûïharry' 'ûò' 'ûówell']
8917


In [97]:
X_transformed= vec.transform(X)
X_transformed


<5572x8917 sparse matrix of type '<class 'numpy.float64'>'
	with 56818 stored elements in Compressed Sparse Row format>

In [98]:
X=X_transformed.toarray()
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [99]:
pd.DataFrame(X, columns=vec.get_feature_names_out())

!    "    #  #150  #5000    $    %         &         '         (  \
0     0.000000  0.0  0.0   0.0    0.0  0.0  0.0  0.000000  0.000000  0.000000   
1     0.000000  0.0  0.0   0.0    0.0  0.0  0.0  0.000000  0.000000  0.000000   
2     0.000000  0.0  0.0   0.0    0.0  0.0  0.0  0.106072  0.137325  0.132367   
3     0.000000  0.0  0.0   0.0    0.0  0.0  0.0  0.000000  0.000000  0.000000   
4     0.000000  0.0  0.0   0.0    0.0  0.0  0.0  0.000000  0.000000  0.000000   
...        ...  ...  ...   ...    ...  ...  ...       ...       ...       ...   
5567  0.098635  0.0  0.0   0.0    0.0  0.0  0.0  0.000000  0.000000  0.000000   
5568  0.000000  0.0  0.0   0.0    0.0  0.0  0.0  0.000000  0.000000  0.000000   
5569  0.000000  0.0  0.0   0.0    0.0  0.0  0.0  0.000000  0.000000  0.000000   
5570  0.000000  0.0  0.0   0.0    0.0  0.0  0.0  0.000000  0.000000  0.000000   
5571  0.000000  0.0  0.0   0.0    0.0  0.0  0.0  0.000000  0.000000  0.000000   

      ...    û   û_  û_thanks  ûªm  ûªt  ûªve   ûï  ûïharry   ûò  ûówell  
0     ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  
1     ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  
2     ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  
3     ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  
4     ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  
...   ...  ...  ...       ...  ...  ...   ...  ...      ...  ...     ...  
5567  ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  
5568  ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  
5569  ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  
5570  ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  
5571  ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  

[5572 rows x 8917 columns]

In [100]:
pd.DataFrame(X, columns=vec.get_feature_names_out())

!    "    #  #150  #5000    $    %         &         '         (  \
0     0.000000  0.0  0.0   0.0    0.0  0.0  0.0  0.000000  0.000000  0.000000   
1     0.000000  0.0  0.0   0.0    0.0  0.0  0.0  0.000000  0.000000  0.000000   
2     0.000000  0.0  0.0   0.0    0.0  0.0  0.0  0.106072  0.137325  0.132367   
3     0.000000  0.0  0.0   0.0    0.0  0.0  0.0  0.000000  0.000000  0.000000   
4     0.000000  0.0  0.0   0.0    0.0  0.0  0.0  0.000000  0.000000  0.000000   
...        ...  ...  ...   ...    ...  ...  ...       ...       ...       ...   
5567  0.098635  0.0  0.0   0.0    0.0  0.0  0.0  0.000000  0.000000  0.000000   
5568  0.000000  0.0  0.0   0.0    0.0  0.0  0.0  0.000000  0.000000  0.000000   
5569  0.000000  0.0  0.0   0.0    0.0  0.0  0.0  0.000000  0.000000  0.000000   
5570  0.000000  0.0  0.0   0.0    0.0  0.0  0.0  0.000000  0.000000  0.000000   
5571  0.000000  0.0  0.0   0.0    0.0  0.0  0.0  0.000000  0.000000  0.000000   

      ...    û   û_  û_thanks  ûªm  ûªt  ûªve   ûï  ûïharry   ûò  ûówell  
0     ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  
1     ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  
2     ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  
3     ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  
4     ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  
...   ...  ...  ...       ...  ...  ...   ...  ...      ...  ...     ...  
5567  ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  
5568  ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  
5569  ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  
5570  ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  
5571  ...  0.0  0.0       0.0  0.0  0.0   0.0  0.0      0.0  0.0     0.0  

[5572 rows x 8917 columns]

In [101]:
df2 = pd.read_csv("/content/drive/MyDrive/Test_spam.csv", encoding='latin-1') 

from sklearn.preprocessing import LabelEncoder

test_numpy_array = df2.values
X_test = test_numpy_array[:, 0]
y_test = test_numpy_array[:, 1]

# Convert y_test labels to integers using LabelEncoder
label_encoder = LabelEncoder()
y_test = label_encoder.fit_transform(y_test)

print("X_test:")
print(X_test)
print("y_test:")
print(y_test)

X_test:
['spam' 'ham' 'ham' 'spam' 'spam' 'ham' 'spam' 'spam' 'ham' 'ham' 'spam'
 'ham']
y_test:
[ 2  1  0 10  3  5  8  9  6  4 11  7]


In [102]:
X_test_transformed=vec.transform(X_test)
X_test_transformed

<12x8917 sparse matrix of type '<class 'numpy.float64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [103]:
X_test=X_test_transformed.toarray()
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [104]:
from sklearn.naive_bayes import MultinomialNB

mnb= MultinomialNB()

mnb.fit(X,y)

mnb.predict_proba(X_test)

array([[0.74398911, 0.25601089],
       [0.87332561, 0.12667439],
       [0.87332561, 0.12667439],
       [0.74398911, 0.25601089],
       [0.74398911, 0.25601089],
       [0.87332561, 0.12667439],
       [0.74398911, 0.25601089],
       [0.74398911, 0.25601089],
       [0.87332561, 0.12667439],
       [0.87332561, 0.12667439],
       [0.74398911, 0.25601089],
       [0.87332561, 0.12667439]])

In [105]:
from sklearn.metrics import accuracy_score   
y_prediction = mnb.predict(X_test)


acc = accuracy_score(y_test, y_prediction)


print("Accuracy:", acc)

Accuracy: 0.08333333333333333
